# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings

title: Sweet Valley Creations
email: dilini.sweetvalleycreations@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Sweet creations from sweetvalleycreations.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.sweetvalleycreations.com" # the base hostname & protocol for your site
twitter_username: sewdil
github_username:  DiliniRajapaksha
twitter:
  username: sewdil
logo: /assets/img/logo.png
# Build settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-redirect-from
permalink: /:categories/:title/
author: https://www.sweetvalleycreations.com
name: sweetvalleycreations.com

collections:
  recipes:
    output: true
    permalink: /recipes/:title/
